services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: statio_db
    volumes:
      - statio_db:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - statio_redis_data:/data
  asynqmon:
    image: hibiken/asynqmon:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
    command: ["--redis-addr=redis:6379"]
    depends_on:
      - redis
volumes:
  statio_db:
  statio_redis_data:
