// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"statio/app"
	"statio/config"
	"statio/container"
	"statio/internal/providers"
)

// Injectors from wire.go:

// InitializeScheduler builds SchedulerContainer
func InitializeScheduler() (*container.SchedulerContainer, error) {
	appConfig, err := config.LoadAppConfig()
	if err != nil {
		return nil, err
	}
	schedulerConfig, err := config.LoadSchedulerConfig()
	if err != nil {
		return nil, err
	}
	redisConfig, err := config.LoadRedisConfig()
	if err != nil {
		return nil, err
	}
	client, err := providers.NewAsyncClient(redisConfig)
	if err != nil {
		return nil, err
	}
	schedulerContainer, err := app.NewAsynqScheduler(appConfig, schedulerConfig, redisConfig, client)
	if err != nil {
		return nil, err
	}
	return schedulerContainer, nil
}
