// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"statio/app"
	"statio/config"
	"statio/container"
	"statio/internal/providers"
	"statio/internal/repositories"
	"statio/internal/services"
	"statio/internal/tasks"
)

// Injectors from wire.go:

// InitializeWorker builds WorkerContainer
func InitializeWorker() (*container.WorkerContainer, error) {
	appConfig, err := config.LoadAppConfig()
	if err != nil {
		return nil, err
	}
	redisConfig, err := config.LoadRedisConfig()
	if err != nil {
		return nil, err
	}
	databaseConfig, err := config.LoadDatabaseConfig()
	if err != nil {
		return nil, err
	}
	db, err := providers.NewDBConnection(databaseConfig)
	if err != nil {
		return nil, err
	}
	tableRepository := repositories.NewTableRepository(db)
	factRepository := repositories.NewFactRepository(db)
	factService := services.NewFactService(factRepository, db)
	dimensionRepository := repositories.NewDimensionRepository(db)
	dimensionService := services.NewDimensionService(dimensionRepository)
	tableService := services.NewTableService(tableRepository, factService, dimensionService, db)
	tableTask := tasks.NewTableTask(tableService)
	workerContainer, err := app.NewAsynqWorker(appConfig, redisConfig, tableTask)
	if err != nil {
		return nil, err
	}
	return workerContainer, nil
}
