// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"statio/app"
	"statio/config"
	"statio/container"
	"statio/internal/handlers"
	"statio/internal/providers"
	"statio/internal/repositories"
	"statio/internal/services"
)

// Injectors from wire.go:

// Initialize App
func InitializeApp() (*container.AppContainer, error) {
	appConfig, err := config.LoadAppConfig()
	if err != nil {
		return nil, err
	}
	databaseConfig, err := config.LoadDatabaseConfig()
	if err != nil {
		return nil, err
	}
	db, err := providers.NewDBConnection(databaseConfig)
	if err != nil {
		return nil, err
	}
	tableRepository := repositories.NewTableRepository(db)
	factRepository := repositories.NewFactRepository(db)
	factService := services.NewFactService(factRepository, db)
	dimensionRepository := repositories.NewDimensionRepository(db)
	dimensionService := services.NewDimensionService(dimensionRepository)
	tableService := services.NewTableService(tableRepository, factService, dimensionService, db)
	validate := providers.NewValidator()
	tableHandler := handlers.NewTableHandler(tableService, validate)
	indicatorRepository := repositories.NewIndicatorRepository(db)
	indicatorService := services.NewIndicatorService(indicatorRepository)
	indicatorHandler := handlers.NewIndicatorHandler(indicatorService, validate)
	dimensionHandler := handlers.NewDimensionHandler(dimensionService, validate)
	appContainer, err := app.NewFiberApp(appConfig, tableHandler, indicatorHandler, dimensionHandler)
	if err != nil {
		return nil, err
	}
	return appContainer, nil
}
