// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"statio/app"
	"statio/config"
	"statio/container"
	"statio/internal/handlers"
	"statio/internal/middlewares"
	"statio/internal/providers"
	"statio/internal/repositories"
	"statio/internal/services"
)

// Injectors from wire.go:

// Initialize App
func InitializeApp() (*container.AppContainer, error) {
	appConfig, err := config.LoadAppConfig()
	if err != nil {
		return nil, err
	}
	authConfig, err := config.LoadAuthConfig()
	if err != nil {
		return nil, err
	}
	jwtService := providers.NewJWTProvider(authConfig)
	jwtMiddleware := middlewares.NewJWTMiddleware(jwtService)
	databaseConfig, err := config.LoadDatabaseConfig()
	if err != nil {
		return nil, err
	}
	db, err := providers.NewDBConnection(databaseConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repositories.NewUserRepository(db)
	userService := services.NewUserService(appConfig, userRepository)
	bpsService := services.NewBPSService()
	authService := services.NewAuthService(userService, jwtService, bpsService)
	validate := providers.NewValidator()
	authHandler := handlers.NewAuthHandler(appConfig, authConfig, authService, validate)
	tableRepository := repositories.NewTableRepository(db)
	factRepository := repositories.NewFactRepository(db)
	factService := services.NewFactService(factRepository, db)
	dimensionRepository := repositories.NewDimensionRepository(db)
	dimensionService := services.NewDimensionService(dimensionRepository)
	excelService := services.NewExcelService()
	aggregationService := services.NewAggregationService(db, tableRepository, dimensionRepository, factRepository)
	redisConfig, err := config.LoadRedisConfig()
	if err != nil {
		return nil, err
	}
	client, err := providers.NewAsyncClient(redisConfig)
	if err != nil {
		return nil, err
	}
	tableService := services.NewTableService(tableRepository, factService, dimensionService, excelService, aggregationService, client, db)
	tableHandler := handlers.NewTableHandler(tableService, validate)
	indicatorRepository := repositories.NewIndicatorRepository(db)
	indicatorService := services.NewIndicatorService(indicatorRepository)
	indicatorHandler := handlers.NewIndicatorHandler(indicatorService, validate)
	dimensionHandler := handlers.NewDimensionHandler(dimensionService, validate)
	organizationRepository := repositories.NewOrganizationRepository(db)
	organizationService := services.NewOrganizationService(organizationRepository, tableService)
	organizationHandler := handlers.NewOrganizationHandler(organizationService, validate)
	userHandler := handlers.NewUserHandler(userService, validate)
	dashboardService := services.NewDashboardService(tableService, factService)
	dashboardHandler := handlers.NewDashboardHandler(dashboardService, validate)
	configurationRepository := repositories.NewConfigurationRepository(db)
	configurationService := services.NewConfigurationService(configurationRepository)
	integrationService := services.NewIntegrationService(tableService, configurationService)
	integrationHandler := handlers.NewIntegrationHandler(integrationService, validate)
	configurationHandler := handlers.NewConfigurationHandler(configurationService, validate)
	appContainer, err := app.NewFiberApp(appConfig, jwtMiddleware, authHandler, tableHandler, indicatorHandler, dimensionHandler, organizationHandler, userHandler, dashboardHandler, integrationHandler, configurationHandler)
	if err != nil {
		return nil, err
	}
	return appContainer, nil
}
